/*
 * ImagePanel.java
 *
 * Created on November 13, 2007, 9:30 AM
 */

package gov.sandia.cognition.generator.matrix.ui;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.ImageObserver;

/**
 *
 * @author  zobenz
 */
public class ImagePanel extends javax.swing.JPanel {
    
    /** Creates new form ImagePanel */
    public ImagePanel() {
        initComponents();       
    }       
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    private Image image;
    private ImageObserver imageObserver;

    public Image getImage()
    {
        return image;
    }

    public void setImage(Image image)
    {
        this.image = image;     
    }        
    
    @Override
    public void paint(Graphics g)
    {
        super.paint(g);
        
        if (image != null)
        {
            Graphics2D g2 = (Graphics2D) g;            
            g2.drawImage(image, 0, 0, imageObserver);        
        }
    }        
}
